### ISSUE TITLE
uncertain on Attention implement?

### ISSUE THREAD

**Issue by chengzhanzhan** [da03/torch-Attention-OCR#1]
I noticed your  [https://github.com/da03/Attention-OCR](Attention-OCR), a very nice project.

I refers to "Grammar as a Foreign Language" for the attention, but I still don't clear  how to compute hidden states of decoder layer in the following figure:
![ocr](https://cloud.githubusercontent.com/assets/8745186/17426486/d5cb5c64-5b0a-11e6-9c97-37c929747b07.jpg)

For the convenience of describing the problem, I draw a simple figure:
![attention](https://cloud.githubusercontent.com/assets/8745186/17426560/c34784ae-5b0b-11e6-99bb-569d2f241904.png)
In this figure, I can compute the glimpse g_t by:
![1](https://cloud.githubusercontent.com/assets/8745186/17426578/ea149a18-5b0b-11e6-9062-4a5a5d8a68b4.png)

![2](https://cloud.githubusercontent.com/assets/8745186/17426581/eec4ebda-5b0b-11e6-8556-8277214ea4d3.png)

![3](https://cloud.githubusercontent.com/assets/8745186/17426582/f18f3028-5b0b-11e6-8810-a889fc09ed54.png)

A question is how to compute y_t by using s_{t-1} and g_t and s_t by using y_t, s_{t-1} and g_t. 
Would you give some illustration on the formula level?

**Comment by da03** [comment]
y_t does not depend on g_t. g_t is concatenated with the embedding of y_t (after linear transformation) as the input to the LSTM cell containing s_t, then s_t would produce y_{t+1}. I would recommend you reading Luong et. al. Effective Approaches to Attention-based Neural Machine Translation, the soft attention mechanism with input feeding, although it is different from the implementation we used here. The reason we used this implementation is that it comes with tensorflow, while we think Luong's formation is more popular.
